### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by stijndcl** [althonos/uniprot.rs#21]
I work with [Unipept](https://unipept.ugent.be/), and as part of our pipeline we parse the SwissProt and TrEMBL files from Uniprot.

We are looking into optimising our Java parser, and were considering re-writing it in Rust using your library. However, it seems to have worse performance than we expected.

The [example from the README](https://github.com/althonos/uniprot.rs#-usage) that simply loops through the XML file takes between **50** and **60** seconds for the SwissProt file using 8 threads (all of which are at 100% usage). This is suspiciously slow. Would you be willing to look into resolving some issues?

Below is a flamegraph to help pointing down the cause (download it & open in your browser to use it interactively): https://gist.github.com/stijndcl/a650e4e20ef3a3e59886a4d5ce8c1b1a

**Comment by althonos** [comment]
Hi @stijndcl,

happy to hear your interest in this. I haven't used this library to parse large files that much (actually mostly to use the UniProt API, and sometimes for one-time only processing of the SwissProt dump), so I didn't focus on the performance that much.

Nevertheless, I had a look and here are the different problems:
- the threads were polling way too agressively from the data queue (every microsecond) so this was causing a super intense CPU usage even when no data was available. I changed the polling delay to 10ms instead (which could be configurable when creating the parser in the future).
- after changing this, i noticed the CPU usage of the background threads dropping to 7%, suggesting that they were idling most of the time. The problem is that the main thread was responsible for both yielding entries and reading from the file; this meant that the background threads had nothing to do most of the time. To fix this, I am experimenting with using a background thread for reading from the file as well, so that the input queue is always full and threads have something to do. Even with this i'm only at 60% max CPU usage in each thread so I have to check what the problem is.
- the parser is *not* zero-copy, it moves everything into owned types, including `Vec` which may contain very few items. I'll see whether i can replace the `Vec` with `arrayvec` or `smallvec` data structures to avoid allocations on most occasions (for instance, most entries have a single accession, so there is no point allocating a `Vec` on the heap to store a single element.

**Comment by stijndcl** [comment]
Thanks for the quick and thorough reply! Could you keep me updated on these?

**Comment by althonos** [comment]
I changed the string types to use `smartstring` in order to avoid allocation for small strings (which is the case for a lot of property types, names or accessions). This should save a bit of runtime and memory.

I'm now getting 20s to parse the whole SwissProt XML file with 8 threads, which is not that bad (350MB/s) considering the parser is unescaping and decoding the XML, and copying everything. 

The bottleneck now seems to be the producer: to be able to process XML entries in parallel, they are sent through a crude tokenizer that looks for `<entry ...>` and `</entry>` tags, and sends the whole data block to a consumer thread when they have been found. Right now, it takes ~17s to read the whole XML file this way, but I'm not sure yet how to improve this.

You can try the `producer-thread` branch if you want to see for yourself :+1:

**Comment by stijndcl** [comment]
Just tried it out on SwissProt and I can confirm:
- My cores are at -70-80% usage instead of the 100% from before
- Execution time for just parsing the file has dropped to ~22 seconds

Parsing by sending chunks to a consumer seems like the best way to go in terms of parallel processing. I doubt you'll be able to improve on that part.

At the end of the day you're still capped by file I/O so I don't think you can get each core to 100% all the time. Simply `cat`ting this file already takes 15-16 seconds for me, so being able to _parse_ it completely in only a few seconds more sounds like you're approaching the lower bound. This is already a massive improvement to me.

I will run it on TrEMBL overnight and I'll report back here tomorrow with the results.

**Comment by stijndcl** [comment]
The results are in. With the old version, processing TrEMBL took about 16.000 - 16.500 seconds (~ 4.5 hours). The current `producer-thread` branch gets through it in just 8.700 seconds (~ 2.4 hours). This new version is indeed a lot faster.

CPU usage is around 40-50% here, but the machine I ran it on has a lot more cores, so file I/O probably can't read it fast enough to provide enough work to all of them.

**Comment by althonos** [comment]
Nice! I also tried different strategies for reading the file (reading entries blocks instead of single entries) which should have reduced the I/O overhead but didn't get any improvement whatsoever.

I think now the remaining performance push could be obtained by changing the data structures to be zero-copy; since now `quick-xml` supports using `Cow` to avoid copying strings that don't need decoding/unescaping, it may be possible to change the data structures to account for that but I can see this require much more work.

**Comment by stijndcl** [comment]
Thanks for your efforts either way, it's very much appreciated!

**Comment by stijndcl** [comment]
@althonos sorry to bother - would you be willing to make a new release soon with the latest changes? It's okay for me if you can't/don't squeeze out the last bits of performance that you mentioned above - I'm aware it can take a lot of time and I'm not expecting you to do those.

**Comment by althonos** [comment]
Hi @stijndcl, I'll try to make a new release shortly 👍

**Comment by althonos** [comment]
Made a `v0.7.0` release with the new code for the producer thread :smile:

**Comment by stijndcl** [comment]
> Made a `v0.7.0` release with the new code for the producer thread 😄

Thank you!
